name: Build Release

on:
  push:
    tags:
      - 'v*'

# on:
#   release:
#     types: [created]

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
    # checkout
    - uses: actions/checkout@master

    - name: get version
      run: |
        export VERSION=$(echo $GITHUB_REF | cut -d/ -f3)
        echo "Version is: ${VERSION}"
        echo "VERSION=${VERSION}" >> $GITHUB_ENV

    # build to ./dist
    - name: compile
      run: sh build-in-docker.sh
      env:
        VERSION: ${{ env.VERSION }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ env.VERSION }}
        release_name: Release ${{ env.VERSION }}
        # body: |
        #   Changes in this Release
        #   - First Change
        #   - Second Change
        draft: false
        prerelease: false

    # Copy build-artifacts in the GitHub release
    - name: Copy build-artifacts
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        releaseId: ${{ env.VERSION }}
        args: "./dist/*"