name: Build Release

on:
  push:
    tags:
      - 'v*'

# on:
#   release:
#     types: [created]

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
    # checkout
    - uses: actions/checkout@master

    # build to ./dist
    - name: compile
      run: sh build-in-docker.sh
        
    - run: |
        set -x
        assets=()
        for asset in ./dist/*; do
          assets+=("-a" "$asset")
        done
        tag_name="${GITHUB_REF##*/}"
        hub release create "${assets[@]}" -m "$tag_name" "$tag_name"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: Create Release
    #   id: create_release
    #   uses: actions/create-release@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
    #   with:
    #     tag_name: ${{ github.ref }}
    #     release_name: Release ${{ env.VERSION }}
    #     # body: |
    #     #   Changes in this Release
    #     #   - First Change
    #     #   - Second Change
    #     draft: false
    #     prerelease: false

    # # Copy build-artifacts in the GitHub release
    # - name: Copy build-artifacts
    #   uses: skx/github-action-publish-binaries@master
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     releaseId: ${{ github.ref }}
    #     args: "./dist/*"